apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-external-dns
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-external-dns
    meta.crossplane.io/description: Installs the kubernetes-sigs external-dns Helm chart for automatic DNS record management.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.1.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
